### ISSUE TITLE
Meta description on sensenet.com

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-resources#27]
Every page should have a custom meta description tag based on the instrucions provided by our SEO analyst: [metadescriptions.txt](https://github.com/SenseNet/sn-resources/files/1088025/metadescriptions.txt)

You don't need to manually input the whole txt, just show a way for how it can be done. 💇 

## Acceptance crit:
- [ ] Title fields can be customized and are set according to the txt 
- [ ] OG:metas are generated automatically
- [ ] Meta description tags are set according to the txt
- [ ] Twitter card related tags are added

**Comment by tusmester** [comment]
_Pages_ contain meta fields that are added to the header if filled. I added the same fields to the _GenericContent_ type (on sncom) as hidden fields and displayed them in the advanced section on several types, so _articles_ also have these fields from now on. The mechanism is _context-based_, so we have to fill these fields on content items (or on a page, if the current content is a page itself).

- **MetaTitle** (_works, tried it_)
- **MetaDescription** (_works, tried it_)
- **MetaAuthors**
- **Keywords**
- **CustomMeta**: must be a well-formed, valid xhtml fragment (_works, tried it_)

**Comment by borsi** [comment]
@tusmester: @balazskeszei is done with the descriptions and titles 👍 
do we have anything else to perform so this would work?

**Comment by tusmester** [comment]
Remove the GTM code that overwrites these values and hope for the best.
(and keep the gunpowder dry)

**Comment by herflis** [comment]
But first wait 'til we publish the updated pagetemplates

**Comment by borsi** [comment]
Waiting for "go" then :)

**Comment by herflis** [comment]
go!
