### ISSUE TITLE
[Demo] Demo materials/tutorials

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-resources#50]
Sandbox requesting seems to be not the perfect way to start to learn sensenet. 

We have to define some main path' for different type of developers with different type of interest (MVC, React, Aurelia, etc). 

Tutorials/Videos:
- [ ] How to install sensenet (7)
- [ ] How to start a React+Redux project with sensenet
- [ ] How to start an Aureliajs project with sensenet
- [ ] How to start a MVC project with sensenet
