### ISSUE TITLE
Roadmap on sensenet.com

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-resources#52]
- [x] Update the roadmap list with the q1 and q2 goals
- [x] Remove the list from 2017
- [x] Set the 2018 q1 one as default
- [x] Create a query/page on the community site with the roadmap related blogposts
- [x] Put a link into the roadmap box on sensenet.com to the post-list

**Comment by iviczl** [comment]
On https://www.sensenet.com/roadmap the 2018 quarters appear in reversed order than the 2017 and there are no spaces between the year number (2018) and the letter Q.
