### ISSUE TITLE
[sncom] Future of the roadmap

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-resources#67]
Maybe it is the right time to rethink and redesing the roadmap on the sensenet.com mainpage.

Questions:
- [x] Should the roadmap be public on the website?
- [x] How our competitors (or other relevant companies) share their roadmap if they share it  at all (best practices)?
- [x] How can we share info about the latest releases (only a link to the changelog or more)?
- [x] How can we share the date of the next releases if we should share them at all? Is there any good examples of that anywhere?

**Comment by CsabaPeter** [comment]
1. There's no need to have a roadmap in the public site or only in the footer as a link. Only one Company (GraphCMS) had a roadmap link on the footer on their website.
![Roadmap](https://user-images.githubusercontent.com/38352683/59768409-9bf00100-92a4-11e9-825c-50d11914f06a.png)

2. Since there was only one company who had a roadmap you can check their display on the following link: https://www.notion.so/63044a76c6224739838e7020eb331914?v=6b794e88db384c57a25a02e985decd0c

3. The latest releases in most company websites are under the news tab or under the blog.
https://www.contentstack.com/blog/product-updates
https://dotcms.com/company/news/
https://www.cloudcms.com/blog.html
https://www.contentful.com/features/
Other companies (Cockpit, Zesty, Genetics Mesh, Cosmic JS) doesn't have any info about new releases

4. There was no next releases tab, blogpost or anything on any of the competitors website
